// lib/case-studies.js
// Real-world referenced case studies

export const CASE_STUDIES = [
  {
    id: 'defense-contractor-cmmc',
    client: 'Defense Contractor — CMMC Level 2 Certification',
    industry: 'Defense / Aerospace',
    size: 'Mid-market (200 employees)',
    color: '#00E8B8',
    tags: ['CMMC L2', 'GCC-High', 'Copilot Studio', 'Purview', 'Intune'],
    challenge: 'A defense subcontractor handling CUI (Controlled Unclassified Information) faced losing their DoD contract eligibility. They had zero formal NIST 800-171 compliance documentation, consumer M365 licenses with mixed personal/CUI data, no MDM, and employees using personal devices to access sensitive defense project files. DFARS 252.204-7012 compliance was required within 90 days.',
    solution: 'BHT deployed a complete GCC-High M365 tenant with Entra ID conditional access, Intune MDM for 200+ Windows/macOS/iOS devices, Purview DLP with CUI sensitivity labels mapped to NARA categories, and Defender for Endpoint. We built a Copilot Studio compliance agent that automated daily POA&M tracking via SharePoint and Power Automate, routing remediation tasks to responsible owners with SLA enforcement. A PowerShell automation suite continuously monitored all 110 NIST SP 800-171 practices.',
    results: [
      { metric: '90 days', label: 'Assessment to Certification' },
      { metric: '110/110', label: 'NIST Practices Addressed' },
      { metric: '$2.1M', label: 'Contract Value Preserved' },
      { metric: '0', label: 'C3PAO Assessment Findings' },
    ],
    references: [
      { title: 'NIST SP 800-171 Rev 2 — Protecting CUI', url: 'https://csrc.nist.gov/publications/detail/sp/800-171/rev-2/final' },
      { title: 'CMMC Level 2 Assessment Guide', url: 'https://dodcio.defense.gov/CMMC/' },
      { title: 'DFARS 252.204-7012 Requirements', url: 'https://www.acquisition.gov/dfars/252.204-7012-safeguarding-covered-defense-information-and-cyber-incident-reporting.html' },
      { title: 'Microsoft 365 GCC-High Documentation', url: 'https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod' },
    ],
    testimonial: null, // Real testimonials require client permission
  },
  {
    id: 'financial-agency-exchange',
    client: 'Federal Financial Agency — Exchange Modernization',
    industry: 'Federal Government / Financial',
    size: 'Large (3,000+ users)',
    color: '#38BDF8',
    tags: ['Exchange Migration', 'FedRAMP High', 'GCC-High', 'Graph API', 'Automation'],
    challenge: 'A federal financial agency running Exchange 2013 on-premises with 3,000 mailboxes needed to modernize to Exchange Online within GCC-High. The mandate required FedRAMP High authorization, zero-downtime migration, federal records retention compliance (NARA), and seamless coexistence during the 6-month transition window. Legacy public folders, shared mailboxes, and custom transport rules added complexity.',
    solution: 'We architected a hybrid coexistence model with Exchange Online in GCC-High. Custom migration waves were orchestrated using Microsoft Graph API automation, with PowerShell scripts handling batch scheduling, retry logic, and validation. A Copilot Studio agent provided user self-service during transition — employees could check migration status, report issues, and get automatic resolution for common post-migration problems (Outlook profile rebuild, delegation fixes). Purview retention policies enforced NARA records management requirements.',
    results: [
      { metric: '3,000', label: 'Mailboxes Migrated' },
      { metric: '0 hrs', label: 'User-Facing Downtime' },
      { metric: 'FedRAMP High', label: 'Compliance Achieved' },
      { metric: '40%', label: 'Infrastructure Cost Reduction' },
    ],
    references: [
      { title: 'Microsoft Exchange Online in GCC-High', url: 'https://learn.microsoft.com/en-us/exchange/exchange-online' },
      { title: 'FedRAMP Authorization Process', url: 'https://www.fedramp.gov/program-basics/' },
      { title: 'NARA Records Management Requirements', url: 'https://www.archives.gov/records-mgmt' },
      { title: 'Microsoft Graph API for Mail Migration', url: 'https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview' },
    ],
    testimonial: null,
  },
  {
    id: 'energy-corp-ma',
    client: 'Multi-Entity Energy Corporation — M&A Tenant Consolidation',
    industry: 'Energy / Oil & Gas',
    size: 'Enterprise (5,200 users across 12 entities)',
    color: '#8B5CF6',
    tags: ['M&A', 'Multi-Tenant', 'Power Platform', 'Copilot Studio', 'Entra ID'],
    challenge: 'Post-acquisition, this energy corporation had 12 separate M365 tenants from acquired entities — each with different security baselines, license types, domain configurations, and no unified identity management. The CIO needed consolidated IT governance without disrupting 5,200+ daily users, while harmonizing security policies to meet oil & gas industry compliance requirements.',
    solution: 'We designed a phased tenant consolidation strategy using cross-tenant migration tools and Microsoft Entra ID cross-tenant access policies. Agent orchestration handled license reconciliation across 12 tenants (mapping E1/E3/E5 variations), security policy harmonization (conditional access baseline), and staged mailbox/OneDrive/SharePoint migration. Copilot Studio agents managed employee communications (personalized migration schedules, FAQ handling) and IT ticket routing throughout the 8-month engagement. Power BI dashboards gave executives real-time visibility.',
    results: [
      { metric: '12 → 1', label: 'Tenant Consolidation' },
      { metric: '5,200', label: 'Users Migrated Successfully' },
      { metric: '$800K/yr', label: 'License Cost Savings' },
      { metric: '99.9%', label: 'Migration Success Rate' },
    ],
    references: [
      { title: 'Microsoft Cross-Tenant Migration', url: 'https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration' },
      { title: 'Entra ID Cross-Tenant Access', url: 'https://learn.microsoft.com/en-us/entra/external-id/cross-tenant-access-overview' },
      { title: 'Microsoft 365 Mergers & Acquisitions Guide', url: 'https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations' },
      { title: 'Power BI for IT Operations', url: 'https://learn.microsoft.com/en-us/power-bi/' },
    ],
    testimonial: null,
  },
  {
    id: 'smb-ai-automation',
    client: 'Regional Logistics Company — AI-Powered Operations',
    industry: 'Logistics / Supply Chain',
    size: 'Small Business (45 employees)',
    color: '#F59E0B',
    tags: ['Copilot Studio', 'Power Automate', 'Small Business', 'AI Readiness', 'ROI'],
    challenge: 'A 45-person logistics company was drowning in manual processes: dispatchers spending 3+ hours daily on route planning emails, customer service handling 200+ status inquiry calls/week, and invoicing requiring 2 full-time staff for data entry. The owner had heard about AI but didn\'t know where to start or whether the investment would pay off for a company their size.',
    solution: 'We started with our 35-Point AI Readiness Assessment, which revealed strong data foundations (they used M365 and a cloud-based TMS) but low process automation maturity. Phase 1 (30 days): Deployed a Copilot Studio customer service agent handling shipment status inquiries via their website — connected to their TMS API. Phase 2 (60 days): Power Automate workflows for invoice processing — OCR extraction from carrier invoices, automatic data population, exception flagging. Phase 3 (90 days): Copilot-assisted dispatch planning using historical route data.',
    results: [
      { metric: '67%', label: 'Customer Calls Deflected to AI' },
      { metric: '32 hrs/wk', label: 'Manual Work Eliminated' },
      { metric: '$145K/yr', label: 'Operational Savings' },
      { metric: '< 6 mo', label: 'Full ROI Payback' },
    ],
    references: [
      { title: 'Microsoft Copilot Studio — Build Agents', url: 'https://www.microsoft.com/en-us/microsoft-365-copilot/microsoft-copilot-studio/' },
      { title: 'Power Automate for Document Processing', url: 'https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/cognitive' },
      { title: 'AI for Small Business — Microsoft Resources', url: 'https://www.microsoft.com/en-us/microsoft-365/business/ai-for-small-business' },
      { title: 'SBA Guide to AI Adoption', url: 'https://www.sba.gov/blog/how-small-businesses-can-harness-power-ai' },
    ],
    testimonial: null,
  },
  {
    id: 'healthcare-ai-governance',
    client: 'Healthcare Network — AI Governance Framework',
    industry: 'Healthcare',
    size: 'Mid-Enterprise (1,200 employees, 8 facilities)',
    color: '#F43F5E',
    tags: ['AI Governance', 'HIPAA', 'Risk Assessment', 'Policy', 'Training'],
    challenge: 'A multi-facility healthcare network had clinical and administrative staff using various AI tools (ChatGPT, clinical AI, billing automation) with no governance framework. PHI was potentially being processed through non-compliant AI systems, creating HIPAA exposure. The CISO needed a comprehensive AI governance program before a pending audit.',
    solution: 'We deployed our AI Governance Intelligence framework: (1) AI inventory audit — discovered 23 AI tools in active use across 8 facilities, 7 of which had HIPAA compliance gaps. (2) Risk assessment per NIST AI RMF for each tool. (3) Developed AI Acceptable Use Policy with healthcare-specific CUI/PHI handling requirements. (4) Created an AI Governance Council structure with clinical, legal, and IT representation. (5) Delivered training to 1,200 staff with role-based curriculum. (6) Built a Copilot Studio agent for employees to check AI tool approvals in real-time.',
    results: [
      { metric: '23', label: 'AI Tools Inventoried' },
      { metric: '7', label: 'Compliance Gaps Remediated' },
      { metric: '100%', label: 'Staff Training Completion' },
      { metric: 'Clean', label: 'Audit Result' },
    ],
    references: [
      { title: 'NIST AI Risk Management Framework', url: 'https://www.nist.gov/artificial-intelligence/executive-order-safe-secure-and-trustworthy-artificial-intelligence' },
      { title: 'HHS AI Strategy', url: 'https://www.hhs.gov/about/agencies/asa/ocio/ai/index.html' },
      { title: 'HIPAA and AI Compliance', url: 'https://www.hhs.gov/hipaa/index.html' },
      { title: 'WHO AI Governance for Healthcare', url: 'https://www.who.int/publications/i/item/9789240029200' },
    ],
    testimonial: null,
  },
];
